### ISSUE TITLE
Velocity Profile generator

### ISSUE THREAD

**Issue by krush11** [TDR-SDC/fsd_simulator#12]
Add a velocity profile generator in the pure_pursuit node file just before velocity is published.
Alternatively, develop the whole controller by making a new package.

**Comment by utkarsh4tech** [comment]
- Implemented a **pure pursuit controller** from scratch with an integrated **longitudinal controller** that receives the planner node path. 
- Added a function to **inject more points** in the path so that the controller can work efficiently. 
- Used a  mathematical function to change velocity according to the steering angle. 
- The pure pursuit node publishes on topic `/robot_control/command`, subscribed by `robot_control` node to drive the car.
